// Original schematic positions: +x east, +z south. Outward quests only.
const place = (id, name, x, z, type, region, description, reading, article = name) => ({
  id, name, x, z, type, region, description, reading,
  source: `https://tolkiengateway.net/wiki/${encodeURIComponent(article.replaceAll(' ', '_'))}`
});
export const locations = [
  place('minas-morgul','Minas Morgul',3.98,4.48,'Fortress','Morgul Vale · Mountains of Shadow','Once Minas Ithil, the Tower of the Moon, this city became the stronghold of the Nazgûl. Frodo and Sam passed nearby on their climb towards Cirith Ungol.','The Two Towers · The Stairs of Cirith Ungol'),
  place('grey-havens', 'Grey Havens', -8.1, -2.3, 'Elven harbour', 'Lindon', 'Círdan’s harbour on the Gulf of Lune. Ships carried the Elves west from here; the Ring-bearers departed at the close of the Third Age.', 'The Return of the King · The Grey Havens'),
  place('bag-end', 'Bag End', -6.5, -2.6, 'Hobbit-hole', 'The Shire', 'Beneath the Hill in Hobbiton lies the home of Bilbo and later Frodo. Both adventures begin at its round front door.', 'The Hobbit · An Unexpected Party'),
  place('old-forest', 'Old Forest', -5.45, -2.0, 'Ancient woodland', 'Eriador', 'Beyond Buckland, the hobbits found paths that seemed to turn against them. Tom Bombadil rescued them from Old Man Willow.', 'The Fellowship of the Ring · The Old Forest'),
  place('bree', 'Bree', -4.65, -2.5, 'Settlement', 'Eriador', 'At the Prancing Pony, Frodo’s companions met the mysterious Strider. Men and hobbits live side by side in this crossroads village.', 'The Fellowship of the Ring · At the Sign of the Prancing Pony'),
  place('weathertop', 'Weathertop', -3.65, -2.75, 'Ruined watchtower', 'Eriador', 'The hill of Amon Sûl once held a great watchtower. Here the Witch-king wounded Frodo with a Morgul blade.', 'The Fellowship of the Ring · A Knife in the Dark'),
  place('trollshaws', 'Trollshaws', -2.65, -3.15, 'Wooded hills', 'Eriador', 'Bilbo’s first encounter with trolls nearly ended the quest. Gandalf kept the three arguing until sunrise turned them to stone.', 'The Hobbit · Roast Mutton'),
  place('rivendell', 'Rivendell', -1.8, -3.3, 'Elven refuge', 'The valley of the Bruinen', 'Elrond’s hidden house sheltered both Bilbo and Frodo. At the Council of Elrond, Frodo accepted the task of carrying the Ring to Mordor.', 'The Fellowship of the Ring · The Council of Elrond'),
  place('high-pass', 'High Pass', -0.8, -3.8, 'Mountain pass', 'Misty Mountains', 'Thorin’s company sought a crossing here and was captured by goblins. In the tunnels below, Bilbo found the Ring and met Gollum.', 'The Hobbit · Over Hill and Under Hill; Riddles in the Dark'),
  place('beorn', 'Beorn’s house', 0.25, -3.35, 'Homestead', 'Anduin Vale', 'The skin-changer Beorn sheltered the company and supplied ponies for the road to Mirkwood.', 'The Hobbit · Queer Lodgings', "Beorn's_Hall"),
  place('mirkwood', 'Mirkwood path', 1.85, -3.35, 'Forest road', 'Northern Mirkwood', 'The company entered a dark forest where leaving the path brought hunger and danger. Bilbo used his sword and the Ring to rescue the dwarves from spiders.', 'The Hobbit · Flies and Spiders', 'Mirkwood'),
  place('woodland-realm', 'Woodland Realm', 3.6, -3.85, 'Elven halls', 'Northern Mirkwood', 'Thranduil’s underground halls became a prison for the dwarves. Bilbo arranged their escape in barrels down the Forest River.', 'The Hobbit · Barrels Out of Bond'),
  place('lake-town', 'Lake-town', 4.62, -2.6, 'Lake settlement', 'Long Lake', 'Built over the water, Esgaroth welcomed Thorin’s company. Smaug later attacked the town and was slain by Bard.', 'The Hobbit · A Warm Welcome; Fire and Water'),
  place('erebor', 'Erebor', 4.55, -3.9, 'Dwarven kingdom', 'The Lonely Mountain', 'Smaug occupied the halls and treasure beneath the mountain. Thorin’s quest reclaimed the kingdom, at the cost of his life in the ensuing battle.', 'The Hobbit · The Gathering of the Clouds; The Clouds Burst'),
  place('hollin', 'Hollin', -2.0, -1.15, 'Lost Elven realm', 'Eregion', 'The Fellowship travelled through the quiet remnants of Eregion. Its ruined realm had once been home to the Elven-smiths who made the Rings of Power.', 'The Fellowship of the Ring · The Ring Goes South', 'Eregion'),
  place('moria', 'Moria', -0.9, -0.5, 'Dwarven halls', 'Misty Mountains', 'The road beneath the mountains led the Fellowship into abandoned Khazad-dûm. Gandalf confronted the Balrog at its narrow bridge.', 'The Fellowship of the Ring · A Journey in the Dark; The Bridge of Khazad-dûm'),
  place('lothlorien', 'Lothlórien', 0.3, -0.15, 'Elven woodland', 'Celebrant valley', 'Galadriel and Celeborn received the Fellowship in the golden wood. Their gifts and boats helped the travellers continue down the Anduin.', 'The Fellowship of the Ring · Farewell to Lórien', 'Lothlórien'),
  place('fangorn', 'Fangorn', -0.25, 1.35, 'Ancient forest', 'Northern Rohan', 'Treebeard and the Ents dwell in this old forest. Merry and Pippin’s arrival helped bring its shepherds into the war against Saruman.', 'The Two Towers · Treebeard'),
  place('isengard', 'Isengard', -1.75, 1.9, 'Fortress', 'Nan Curunír · south of Methedras', 'The tower of Orthanc stands inside a great stone ring. Saruman made it a war machine until the Ents broke its walls and flooded its works.', 'The Two Towers · The Road to Isengard'),
  place('helms-deep', 'Helm’s Deep', -1.6, 2.85, 'Fortified valley', 'Rohan', 'The Hornburg guards the Deeping-coomb. Théoden’s defenders held out here against Saruman’s army until help arrived at dawn.', 'The Two Towers · Helm’s Deep', "Helm's_Deep"),
  place('edoras', 'Edoras', -0.3, 3.0, 'Royal seat', 'Rohan', 'The golden hall of Meduseld overlooks the plains. Here Gandalf helped Théoden shake off Gríma’s influence and return to his people.', 'The Two Towers · The King of the Golden Hall'),
  place('amon-hen', 'Amon Hen', 1.65, 1.75, 'Hill of seeing', 'Nen Hithoel', 'The Fellowship broke near the falls of Rauros. Frodo set out for Mordor, and Sam refused to let him go alone.', 'The Fellowship of the Ring · The Breaking of the Fellowship'),
  place('emyn-muil', 'Emyn Muil', 2.65, 1.8, 'Broken hill country', 'East of the Anduin', 'Frodo and Sam struggled through steep, confusing hills before capturing Gollum and accepting him as their guide.', 'The Two Towers · The Taming of Sméagol'),
  place('dead-marshes', 'Dead Marshes', 3.25, 2.2, 'Marshland', 'Northwest of Mordor', 'Gollum led the hobbits past pale lights and faces beneath the water. These haunted wetlands preserve the memory of ancient battles.', 'The Two Towers · The Passage of the Marshes'),
  place('black-gate', 'Black Gate', 4.15, 2.55, 'Fortified gate', 'Morannon', 'The guarded entrance to Mordor proved impossible for Frodo to cross. Gollum offered another way, south through Ithilien.', 'The Two Towers · The Black Gate Is Closed'),
  place('henneth-annun', 'Henneth Annûn', 3.65, 3.25, 'Hidden refuge', 'Ithilien', 'Behind a waterfall, Faramir’s Rangers sheltered the hobbits. Faramir let them continue their perilous errand.', 'The Two Towers · The Window on the West', 'Henneth_Annûn'),
  place('minas-tirith', 'Minas Tirith', 2.65, 4.35, 'City of Gondor', 'Anórien', 'The White City stands against Mount Mindolluin. The siege and the battle on the Pelennor Fields decided the fate of Gondor.', 'The Return of the King · The Siege of Gondor'),
  place('cirith-ungol', 'Cirith Ungol', 4.15, 4.3, 'Mountain pass', 'Mountains of Shadow', 'The hidden approach to Mordor led through Shelob’s lair. Sam rescued Frodo from the tower beyond the pass.', 'The Two Towers · Shelob’s Lair; The Return of the King · The Tower of Cirith Ungol'),
  place('mount-doom', 'Mount Doom', 5.35, 3.45, 'Volcano', 'Gorgoroth · Mordor', 'The Ring was forged in the fire of Orodruin. When Gollum fell into the fire with it, Sauron’s power was broken.', 'The Return of the King · Mount Doom'),
  place('barad-dur', 'Barad-dûr', 6.65, 3.1, 'Dark tower', 'Mordor', 'Sauron’s fortress dominated the plateau of Gorgoroth. Its foundations depended on the Ring and collapsed when the Ring was destroyed.', 'The Return of the King · Mount Doom', 'Barad-dûr')
];
export const journeys = {
  frodo: { name: 'Frodo’s road', color: 0xf08a63, period: 'TA 3018–3019', points: ['bag-end','old-forest','bree','weathertop','trollshaws','rivendell','hollin','moria','lothlorien','amon-hen','emyn-muil','dead-marshes','black-gate','henneth-annun','minas-morgul','cirith-ungol','mount-doom'] },
  bilbo: { name: 'Bilbo’s road', color: 0xf3cf78, period: 'TA 2941', points: ['bag-end','trollshaws','rivendell','high-pass','beorn','mirkwood','woodland-realm','lake-town','erebor'] }
};
export const events = [
  { id:'last-alliance', place:'black-gate', name:'Battle of Dagorlad', date:'SA 3434', description:'The Last Alliance defeated Sauron’s forces on the plain before Mordor and advanced to besiege Barad-dûr.', reading:'The Fellowship of the Ring · The Council of Elrond', article:'Battle_of_Dagorlad' },
  { id:'five-armies', place:'erebor', name:'Battle of Five Armies', date:'TA 2941', description:'Dwarves, Elves and Men united against the goblins and Wargs at the Lonely Mountain. Thorin fell in the battle.', reading:'The Hobbit · The Clouds Burst', article:'Battle_of_Five_Armies' },
  { id:'knife', place:'weathertop', name:'Attack on Weathertop', date:'6 October · TA 3018', description:'The Witch-king stabbed Frodo. The wound made the race to Elrond’s refuge urgent.', reading:'The Fellowship of the Ring · A Knife in the Dark', article:'Attack_on_Weathertop' },
  { id:'bridge', place:'moria', name:'The fall of Gandalf', date:'15 January · TA 3019', description:'Gandalf broke the bridge beneath the Balrog, but its whip caught him as it fell. The others escaped from Moria.', reading:'The Fellowship of the Ring · The Bridge of Khazad-dûm', article:'Battle_of_the_Peak' },
  { id:'hornburg', place:'helms-deep', name:'Battle of the Hornburg', date:'3–4 March · TA 3019', description:'Rohan’s defenders survived the assault on Helm’s Deep. Gandalf arrived with Erkenbrand and reinforcements at dawn.', reading:'The Two Towers · Helm’s Deep', article:'Battle_of_the_Hornburg' },
  { id:'ents', place:'isengard', name:'The Ents march', date:'2–3 March · TA 3019', description:'Treebeard led the Ents against Isengard, destroying Saruman’s workshops and trapping him in Orthanc.', reading:'The Two Towers · Flotsam and Jetsam', article:'Destruction_of_Isengard' },
  { id:'pelennor', place:'minas-tirith', name:'Battle of the Pelennor Fields', date:'15 March · TA 3019', description:'The Rohirrim and the forces of Gondor broke the siege. Éowyn and Merry brought down the Witch-king.', reading:'The Return of the King · The Battle of the Pelennor Fields', article:'Battle_of_the_Pelennor_Fields' },
  { id:'ring', place:'mount-doom', name:'The destruction of the Ring', date:'25 March · TA 3019', description:'The Ring and Gollum fell into the Cracks of Doom. Sauron was defeated, bringing the War of the Ring to its turning point.', reading:'The Return of the King · Mount Doom', article:'Destruction_of_the_One_Ring' },
  { id:'siege-barad-dur', place:'barad-dur', name:'The Siege of Barad-dûr', date:'SA 3434–3441', description:'Gil-galad and Elendil perished in overthrowing Sauron. Isildur cut the One Ring from Sauron’s hand.', reading:'The Fellowship of the Ring · The Council of Elrond', article:'Siege_of_Barad-d%C3%BBr', dx:.24, dz:.14 },
  { id:'morannon-stand', place:'black-gate', name:'Battle of the Morannon', date:'25 March · TA 3019', description:'Aragorn and the Host of the West made their stand before the Black Gate to draw Sauron’s Eye away from Mount Doom.', reading:'The Return of the King · The Black Gate Opens', article:'Battle_of_the_Morannon', dx:-.18, dz:-.14 },
  { id:'bywater-battle', place:'bag-end', name:'The Battle of Bywater', date:'3 November · TA 3019', description:'Merry and Pippin rallied the hobbits to defeat Saruman’s ruffians in the final conflict of the War of the Ring.', reading:'The Return of the King · The Scouring of the Shire', article:'Battle_of_Bywater', dx:.26, dz:.15 },
  { id:'coronation', place:'minas-tirith', name:'Coronation of King Elessar', date:'1 May · TA 3019', description:'Gandalf crowned Aragorn as King of both Gondor and Arnor, inaugurating the reunited realm and the Fourth Age.', reading:'The Return of the King · The Steward and the King', article:'Aragorn_II', dx:-.16, dz:-.15 },
  { id:'amon-sul-fall', place:'weathertop', name:'The Fall of Amon Sûl', date:'TA 1409', description:'The Witch-king’s army burned the great watchtower and slew King Arveleg I. The palantír was saved and brought to Fornost.', reading:'The Return of the King · Appendix A', article:'Weathertop', dx:-.18, dz:.15 },
  { id:'breaking-fellowship', place:'amon-hen', name:'The Breaking of the Fellowship', date:'26 February · TA 3019', description:'Boromir fell defending Merry and Pippin from Saruman’s Uruk-hai on the wooded slopes of Amon Hen.', reading:'The Two Towers · The Departure of Boromir', article:'Boromir', dx:.18, dz:-.18 },
  { id:'council-elrond', place:'rivendell', name:'The Council of Elrond', date:'25 October · TA 3018', description:'Frodo took the burden of the Ring, and the Nine Walkers were chosen to represent the Free Peoples of Middle-earth.', reading:'The Fellowship of the Ring · The Council of Elrond', article:'Council_of_Elrond', dx:.20, dz:-.15 }
].map(event => { const location = locations.find(p => p.id === event.place); return { ...event, x:location.x + (event.dx ?? .22), z:location.z + (event.dz ?? -.16), type:'Notable event', region:event.date, source:`https://tolkiengateway.net/wiki/${event.article}` }; });
export const regions = [ ['E R I A D O R',-4.8,-.35], ['R H O V A N I O N',3,-1.3], ['R O H A N',-.25,2.4], ['G O N D O R',.2,4.8], ['M O R D O R',6.2,4.8], ['M I R K W O O D',2.3,-2.3], ['B E L E G A E R',-8.7,2.7], ['F O R O D W A I T H',1.0,-8.0], ['O R O C A R N I',12.8,1.0] ];
