// Book-based features, placed schematically in the atlas coordinate system.
// Paths/area anchors are interpretive; they are not surveyed borders or courses.
const entry=(id,name,x,z,type,region,description,article=name,level=1)=>({id,name,x,z,type,region,description,level,
  reading:'The Lord of the Rings · maps; see the linked article for chapter references.',
  source:`https://tolkiengateway.net/wiki/${encodeURIComponent(article.replaceAll(' ','_'))}`});
export const localPlaces=[
  entry('pelargir','Pelargir',2.2,5.2,'Harbour','Gondor · Anduin','Gondor’s ancient river port, where Aragorn took the fleet of the Corsairs.','Pelargir',0),
  entry('umbar','Umbar',.65,10.1,'Haven','Harad coast','A great southern haven associated with the Corsairs who raided Gondor.','Umbar',0),
  entry('dol-amroth','Dol Amroth',-1.6,6.17,'City','Gondor · Belfalas','The coastal seat of Prince Imrahil, whose knights fought for Minas Tirith.','Dol Amroth',0),
  entry('dunharrow','Dunharrow',-.35,3.46,'Mountain refuge','Rohan · Harrowdale','A refuge above Harrowdale, reached by a climbing road. The Rohirrim gathered here before riding to Gondor.'),
  entry('harrowdale','Harrowdale',-.4,3.26,'Valley','Rohan · The Folde','The Snowbourn runs north through this valley in the White Mountains, towards Edoras.'),
  entry('aldburg','Aldburg',.35,3.18,'Settlement','Rohan · The Folde','Eorl’s early seat in Rohan. The royal household later moved to Edoras; Éomer dwelt here before becoming king.'),
  entry('fords-isen','Fords of Isen',-2.1,2.5,'River crossing','Rohan · Western border','A strategic crossing on the Isen. Théodred fell in the fighting here during Saruman’s invasion.','Fords of Isen'),
  entry('entwade','Entwade',.65,2.65,'River crossing','Rohan · Entwash','A ford across the Entwash northeast of Edoras. Roads across the plains converged on this crossing.'),
  entry('deeping-coomb','Deeping-coomb',-1.7,3.04,'Valley','Rohan · Westfold','The valley leading towards Helm’s Deep. Its stream flows out through the defences of the Hornburg.'),
  entry('aglarond','Glittering Caves',-1.75,3.24,'Caverns','Rohan · Helm’s Deep','The caverns behind Helm’s Deep astonished Gimli. After the war he became lord of the Dwarves who settled there.','Aglarond',2),
  entry('starkhorn','Starkhorn',-.55,3.73,'Mountain','Rohan · White Mountains','The snowy peak at the head of Harrowdale, beneath which the Snowbourn rises.','Starkhorn',2),
  entry('halifirien','Halifirien',1.3,3.7,'Beacon hill','Rohan / Gondor border','A beacon above the Firien Wood. Cirion and Eorl swore their oath of friendship at this sacred hill.'),
  entry('wellinghall','Wellinghall',-.85,1.13,'Ent dwelling','Fangorn Forest','Treebeard’s home near the headwaters of the Entwash, where he sheltered Merry and Pippin.','Wellinghall',2),
  entry('parth-galen','Parth Galen',1.52,1.64,'Lakeside lawn','Western shore of Nen Hithoel','The Fellowship camped on this green lawn before its members were scattered.','Parth Galen',2),
  entry('rauros','Rauros',1.76,1.98,'Waterfall','Anduin · Emyn Muil','The Anduin plunges from Nen Hithoel over these falls. Boromir’s funeral boat passed over them.'),
  entry('argonath','Argonath',1.4,1.13,'Monument','Anduin · Northern Nen Hithoel','The great figures of Isildur and Anárion mark the ancient northern boundary of Gondor.'),
  entry('osgiliath','Osgiliath',2.9,4.1,'Ruined city','Gondor · Anduin','The former capital of Gondor straddled the Anduin. Its ruined crossings became a front line in the War of the Ring.','Osgiliath',0),
  entry('buckland','Buckland',-5.82,-2.05,'Settled district','The Shire / Eriador','The Brandybucks settled east of the Brandywine, between the river and the Old Forest.'),
  entry('bywater','Bywater',-6.23,-2.45,'Village','The Shire','A village near Hobbiton, and the scene of the hobbits’ stand against the ruffians during the Scouring of the Shire.','Bywater',2),
  entry('last-bridge','Last Bridge',-3.05,-3.06,'Bridge','Eriador · Hoarwell','The East Road crosses the Hoarwell here, west of the Trollshaws.','Last Bridge',2),
  entry('ford-bruinen','Ford of Bruinen',-2.03,-3.04,'River crossing','Eriador · Rivendell','Floodwaters swept away the pursuing Nazgûl as Frodo reached the border of Elrond’s refuge.','Ford of Bruinen',2),
  entry('tharbad','Tharbad',-3.65,.15,'Ruined crossing','Eriador · Greyflood','A once-important settlement at the crossing of the Greyflood. Boromir lost his horse while passing here.'),
  entry('dale','Dale',4.64,-4.35,'City','Rhovanion · Erebor','The town south of the Lonely Mountain was destroyed by Smaug and rebuilt under Bard after the dragon’s death.'),
  entry('carrock','Carrock',.4,-3.62,'River rock','Rhovanion · Anduin','A great rock in the Anduin near Beorn’s lands. The Eagles brought Bilbo and the dwarves here.','Carrock',2),
  entry('dol-guldur','Dol Guldur',2.0,-.46,'Fortress','Southern Mirkwood','Sauron occupied this stronghold as the Necromancer before openly returning to Mordor.'),
  entry('gladden-fields','Gladden Fields',.68,-1.72,'Wetlands','Rhovanion · Anduin','Isildur was ambushed in this region after the Last Alliance. The Ring was lost in the Anduin nearby.'),
  entry('annuminas','Annúminas',-6.4,-4.0,'Ancient city','Arnor · Lake Evendim','The first capital of Arnor, founded by Elendil on the shores of Lake Evendim. Restored by King Elessar.','Annúminas',0),
  entry('fornost','Fornost',-5.1,-3.8,'Ruined city','Arthedain · North Downs','The Norbury of the Kings became the second capital of Arnor until the Witch-king captured it in Third Age 1974.','Fornost',1),
  entry('barrow-downs','Barrow-downs',-5.05,-2.15,'Ancient barrows','Tyrn Gorthad · Eriador','Mounds of ancient kings haunted by Barrow-wights. Tom Bombadil rescued the hobbits, who took blades of Westernesse.','Barrow-downs',1),
  entry('michel-delving','Michel Delving',-7.2,-2.55,'Town','The Shire · White Downs','The chief town of the Shire, seat of the Mayor and home to the Mathom-house where old curiosities were kept.','Michel_Delving',1),
  entry('crickhollow','Crickhollow',-5.65,-2.12,'Hobbit dwelling','Buckland · The Shire','The quiet house Frodo bought to conceal his departure from the Shire. Fredegar Bolger stayed behind to keep up appearances.','Crickhollow',2),
  entry('carn-dum','Carn Dûm',-1.6,-5.8,'Fortress','Angmar · Mountains of Angmar','The chief fortress of the Witch-king of Angmar, who led the long wars that destroyed the kingdoms of Arnor.','Carn_Dûm',0),
  entry('gundabad','Mount Gundabad',-.9,-5.35,'Sacred peak & fortress','Northern Misty Mountains','Sacred to the Dwarves as the awakening place of Durin the Deathless, later occupied as a major goblin stronghold.','Mount_Gundabad',0),
  entry('rhosgobel','Rhosgobel',1.15,-1.95,'Wizard’s dwelling','Southern Greenwood · Anduin Vale','The home of Radagast the Brown, who dwelt among the beasts and birds near the western eaves of Mirkwood.','Rhosgobel',1),
  entry('dimrill-dale','Dimrill Dale',-.65,-.45,'Valley','Azanulbizar · Misty Mountains','Nanduhirion lies outside the East Gate of Moria. Scene of the great battle between Dwarves and Orcs where Azog was slain.','Dimrill_Dale',1),
  entry('mirrormere','Mirrormere',-.58,-.38,'Sacred lake','Kheled-zâram · Dimrill Dale','Durin looked into this still dark lake and saw a crown of stars above his reflection, leading him to found Khazad-dûm.','Mirrormere',2),
  entry('redhorn-gate','Redhorn Gate',-1.2,-1.0,'Mountain pass','Caradhras · Misty Mountains','The high pass over the Redhorn beneath Caradhras. Fierce blizzards forced the Fellowship to turn back towards Moria.','Redhorn_Gate',1),
  entry('ost-in-edhil','Ost-in-Edhil',-2.35,-.9,'Ruined Elven city','Eregion · Hollin','The capital of Eregion where Celebrimbor and the Gwaith-i-Mírdain dwelt and forged the Rings of Power with Sauron’s aid.','Ost-in-Edhil',1),
  entry('field-celebrant','Field of Celebrant',.9,.1,'Historic battlefield','Between Silverlode and Limlight','Here Eorl the Young led the Éothéod in relief of Gondor in TA 2510, earning the land of Calenardhon that became Rohan.','Field_of_Celebrant',1),
  entry('cair-andros','Cair Andros',2.5,3.55,'Fortified island','Anduin · Gondor','An island shaped like a great ship that guarded the river passage above Osgiliath against crossings from the east.','Cair_Andros',0),
  entry('pelennor-fields','Pelennor Fields',2.75,4.45,'Plain & battlefield','Anórien · Minas Tirith','The townlands of Minas Tirith within the Rammas Echor wall. Scene of the battle where the Witch-king fell.','Pelennor_Fields',1),
  entry('harlond-gondor','Harlond',2.7,4.65,'River haven','Anduin · Pelennor','The quays of Minas Tirith on the Anduin, where Aragorn landed the captured black fleet to turn the battle.','Harlond_(Gondor)',2),
  entry('paths-dead','Paths of the Dead',-.45,3.65,'Haunted passage','White Mountains · Dwimorberg','A dark road beneath the mountains. Aragorn passed through to summon the Oathbreakers at the Stone of Erech.','Paths_of_the_Dead',2),
  entry('erech','Stone of Erech',-.65,4.35,'Black stone monument','Blackroot Vale · Morthond','A massive black stone brought from Númenor by Isildur, where the King of the Mountains swore and broke his oath.','Stone_of_Erech',1),
  entry('calembel','Calembel',.15,4.95,'Settlement','Lamedon · Gondor','The chief town of Lamedon on the river Ciril, passed by Aragorn and the Grey Company as they hurried to Pelargir.','Calembel',1),
  entry('linhir','Linhir',1.15,5.85,'River crossing','Gilrain · Lebennin','A haven and crossing near the mouth of the Gilrain where the defenders of Lebennin fought off the Haradrim.','Linhir',1),
  entry('tolfalas','Tolfalas',-.3,7.2,'Island','Bay of Belfalas · Mouths of Anduin','A great rugged island standing in the Bay of Belfalas off the delta of the Great River.','Tolfalas',0),
  entry('durthang','Durthang',4.35,2.9,'Fortress','Ephel Dúath · Mordor','An ancient castle of Gondor built to watch Mordor, later used as an orc stronghold in northern Mordor.','Durthang',1),
  entry('carach-angren','Carach Angren',4.85,3.1,'Fortified pass','Isenmouthe · Mordor','The Isenmouthe: a narrow gorge defended by ramparts, connecting the valley of Udûn with Gorgoroth.','Carach_Angren',1),
  entry('lond-daer','Lond Daer',-7.2,2.45,'Ancient haven','Enedwaith · Mouth of Greyflood','An ancient haven built by King Aldarion of Númenor for timber-shipping, once called the Great Middle Haven.','Lond_Daer',1),
  entry('withered-heath','Withered Heath',6.3,-5.1,'Highland valley','Ered Mithrin · Grey Mountains','A desolate plateau in the eastern Grey Mountains, known as the breeding ground of the great dragons.','Withered_Heath',1)
];
export const localAreas=[
  entry('iron-hills','Iron Hills',8.3,-4.7,'Hill country','Eastern Rhovanion','Dwarven country east of Erebor. Dáin Ironfoot led warriors from here to the Battle of Five Armies.','Iron Hills',0),
  entry('rhun-region','Rhûn',11.45,-.4,'Region','Eastern lands','The broad eastern lands beyond Rhovanion. Their full extent is not mapped in this atlas.','Rhûn',0),
  entry('nurn','Nurn',7.0,6.9,'Region','Southern Mordor','The fields around Lake Núrnen supplied Sauron’s armies through the labour of enslaved people.','Nurn',0),
  entry('south-gondor','South Gondor',3.22,7.0,'Borderland','Harondor · between Poros and Harnen','The country between the Poros and Harnen was disputed between Gondor and the peoples of Harad.','South Gondor',0),
  entry('near-harad','Near Harad',5.1,9.65,'Region','Harad · south of the Harnen','The northern part of Harad, south of Gondor and Mordor and west of Khand. Its limits are approximate.','Near Harad',0),
  {...entry('harad','Harad · Sutherland',6.5,11.6,'Southern lands','Haradwaith · the South','Harad, or the South, is also called Sutherland. This label denotes the wider southern lands, not a separate kingdom. Only their northern portion is shown.','Harad',0),aliases:['Sutherland','Southland','Haradwaith'],source:'https://www.glyphweb.com/arda/s/south.php'},
  entry('khand','Khand',12.6,9.2,'Region','Southeast of Mordor','The land of the Variags, southeast of Mordor and east of Near Harad. Its borders are not precisely defined here.','Khand',0),
  entry('belfalas','Belfalas',-1.35,5.66,'Coastal region','Gondor','A southern fief of Gondor adjoining the great bay, with Dol Amroth on its coast.','Belfalas'),
  entry('lebennin','Lebennin',1.0,5.47,'Province','Gondor','The land of five streams west of the lower Anduin.','Lebennin'),
  entry('morgul-vale','Morgul Vale',3.8,4.65,'Valley','Western approaches to Mordor','The valley of Minas Morgul lies below the high pass of Cirith Ungol.','Morgul Vale'),
  entry('nan-curunir','Nan Curunír',-1.72,2.13,'Valley','Rohan · Isengard','The Wizard’s Vale at the southern end of the Misty Mountains, containing Isengard.','Nan Curunír',2),
  entry('westfold','Westfold',-1.43,2.54,'District','Rohan','The western settled lands beneath the White Mountains, stretching east from the Isen towards the Folde.'),
  entry('folde','The Folde',-.02,3.1,'District','Rohan','The heartland of the royal house around Edoras and Aldburg.','Folde'),
  entry('eastfold','Eastfold',.87,3.33,'District','Rohan','The lands between the Entwash and the White Mountains, east of the Folde and west of the Fenmarch.'),
  entry('westemnet','Westemnet',-.64,2.15,'Grasslands','Rohan','The western plains of Rohan, west of the Entwash.'),
  entry('eastemnet','Eastemnet',1.04,2.09,'Grasslands','Rohan','The eastern plains of Rohan, on the opposite side of the Entwash from the Westemnet.'),
  entry('wold','The Wold',.91,.95,'Uplands','Rohan','The northern uplands of Rohan, south of the Limlight.','Wold'),
  entry('west-march','West-march',-2.88,2.94,'Borderland','Rohan','The western borderland between the Isen and the Adorn.'),
  entry('fenmarch','Fenmarch',1.38,3.37,'Border district','Rohan','The eastern border country near the marshes and the Mering Stream.'),
  entry('gap-rohan','Gap of Rohan',-2.37,2.07,'Mountain gap','Rohan / Enedwaith','The passage between the southern Misty Mountains and the White Mountains.','Gap of Rohan'),
  entry('entwash-mouths','Mouths of Entwash',1.69,2.97,'River delta','Rohan / Gondor','The Entwash divides into marshy channels before joining the Anduin.','Mouths of Entwash'),
  entry('anorien','Anórien',2.02,3.72,'Province','Gondor','The land north of the White Mountains, between Rohan and Minas Tirith.','Anórien'),
  entry('ithilien','Ithilien',3.56,3.88,'Province','Gondor','The lands between the Anduin and Mordor’s western mountains. Faramir’s Rangers held hidden refuges here.'),
  entry('dunland','Dunland',-3.2,1.48,'Region','Enedwaith','The land west of the southern Misty Mountains, home to the Dunlendings.'),
  entry('southfarthing','Southfarthing',-6.4,-1.89,'District','The Shire','The southern division of the Shire, known for its pipe-weed.'),
  entry('northfarthing','Northfarthing',-6.57,-3.23,'District','The Shire','The northern division of the Shire, with cooler upland country.'),
  entry('gorgoroth','Gorgoroth',5.93,3.71,'Volcanic plateau','Mordor','The desolate plateau surrounding Mount Doom and the approaches to Barad-dûr.'),
  entry('ered-mithrin','Ered Mithrin',2.8,-5.2,'Mountain range','Northern Wilderland','The Grey Mountains, running east from Mount Gundabad. Ancient home to Dwarven mansions abandoned to dragons.','Ered_Mithrin',0),
  entry('angmar-region','Angmar',-2.0,-5.6,'Northern realm','North of the Misty Mountains','The realm of the Witch-king, established in the Third Age to destroy the divided Dúnedain kingdoms of Arnor.','Angmar',0),
  entry('north-downs','North Downs',-4.8,-3.5,'Hills','Eriador · Arthedain','A range of green hills where the kings of Arthedain ruled from Fornost after the fall of Annúminas.','North_Downs'),
  entry('westfarthing','Westfarthing',-6.8,-2.45,'District','The Shire','The most populous division of the Shire, containing Hobbiton, Bywater, Michel Delving and the White Downs.','Westfarthing'),
  entry('eastfarthing','Eastfarthing',-5.8,-2.4,'District','The Shire','The eastern division of the Shire, bordering the Brandywine and containing the Marish and the bridge.','Eastfarthing'),
  entry('lossarnach','Lossarnach',2.05,4.6,'Fief of Gondor','Valleys of the White Mountains','A fertile fief in the valleys of Mount Mindolluin, famed for its flowery orchards. Lord Forlong led its axemen.','Lossarnach'),
  entry('lamedon','Lamedon',.1,4.85,'Fief of Gondor','Southern White Mountains','A mountainous fief on the southern slopes of the White Mountains, centered around the river Ciril.','Lamedon'),
  entry('pinnath-gelin','Pinnath Gelin',-3.6,5.4,'Fief of Gondor','Green Hills · Western Gondor','The Green Hills of western Gondor. Hirluin the Fair brought three hundred gallant men in green to Minas Tirith.','Pinnath_Gelin'),
  entry('udun-mordor','Udûn',4.45,2.8,'Valley','Northern Mordor','The deep circular valley behind the Black Gate, where Sauron’s armies massed before passing through the Morannon.','Udûn_(Mordor)'),
  entry('lithlad','Lithlad',8.8,4.8,'Plain of Ash','Southeastern Mordor','The vast Plain of Ash in southern Mordor, west of Khand and north of the cultivated plains of Nurn.','Lithlad',0),
  entry('emyn-arnen','Emyn Arnen',3.3,4.7,'Hills','Central Ithilien','The Hills of Arnen in Ithilien, home to the line of the Stewards. Seat of Prince Faramir after the war.','Emyn_Arnen'),
  entry('ethir-anduin','Ethir Anduin',-.1,6.8,'River mouths / Delta','Bay of Belfalas · Gondor','The broad delta where the Anduin divides into many channels and flows out into the Bay of Belfalas.','Ethir_Anduin')
].map(area=>({...area,area:true}));
const river=(id,name,region,points,description,level=1,article=name,joins)=>({
  ...entry(id,name,...points[Math.floor(points.length/2)],'River',region,description,article,level),points,joins,width:level===0?.024:.014
});
export const rivers=[
  {...river('nurnen-west','Unnamed river · western Nurn','Mordor',[[4.75,6.7],[5.65,6.4],[6.2,6.02],[7.05,6.0]],'An unnamed feeder of Lake Núrnen. The course is schematic; the descriptive label is not a Tolkien place-name.',1,'Sea of Núrnen'),joinsLake:'nurnen'},
  {...river('nurnen-south','Unnamed river · southern Nurn','Mordor',[[7.5,8.15],[7.1,7.5],[7.5,6.95],[7.8,6.48]],'One of the unnamed rivers draining the southern Mountains of Shadow into Núrnen.',1,'Sea of Núrnen'),joinsLake:'nurnen'},
  {...river('nurnen-north','Unnamed river · northern Nurn','Mordor',[[9.35,3.95],[8.6,4.35],[7.5,4.9],[7.6,5.69]],'A schematic feeder descending from Mordor’s interior mountain spur to Núrnen.',1,'Sea of Núrnen'),joinsLake:'nurnen'},
  {...river('nurnen-east','Unnamed river · eastern Nurn','Mordor',[[9.7,3.35],[10.25,4.4],[9.6,5.3],[8.82,5.97]],'A second unnamed feeder from the spur of the Ash Mountains. Its course here is approximate.',1,'Sea of Núrnen'),joinsLake:'nurnen'},
  river('harnen','Harnen','Harad / South Gondor',[[4.9,8],[4.1,8.25],[2.8,8.37],[1.4,8.43],[.1,8.5]],'The Harnen runs west towards the sea, separating South Gondor from Near Harad.',0,'Harnen'),
  river('poros','Poros','Gondor / South Gondor',[[4.59,5.6],[4,5.75],[3.08,5.96],[1.62,5.78]],'The Poros forms the northern boundary of South Gondor and flows into the lower Anduin.',1,'Poros','anduin'),
  river('carnen','Carnen','Eastern Rhovanion',[[8.1,-4.6],[7.85,-3.7],[7.45,-2.76],[6.7,-1.84],[5.8,-1.3]],'The Redwater flows south from the Iron Hills to join the Running River.',0,'Carnen','running'),
  river('morgulduin','Morgulduin','Ithilien',[[4.22,4.46],[3.98,4.48],[3.51,4.37],[3.18,4.31],[2.55,4.55]],'The stream of the Morgul Vale descends from Minas Morgul towards the Anduin.',1,'Morgulduin','anduin'),
  river('anduin','Anduin','Rhovanion / Gondor',[[.1,-5.4],[.28,-4.4],[.45,-3.7],[.58,-2.7],[.75,-2.1],[.82,-1.4],[.9,-.3],[1.14,.4],[1.4,.8],[1.4,1.13],[1.65,1.75],[1.76,1.98],[2,2.8],[2.24,3.2],[2.9,4.1],[2.55,4.55],[2.2,5.2],[1.62,5.78],[.8,6.3],[-.55,6.65]],'The Great River links the northern vales with Gondor, passing Lórien, Rauros and the fields below Minas Tirith.',0),
  river('brandywine','Brandywine','The Shire / Eriador',[[-6.22,-4.18],[-6,-3.72],[-5.85,-3.1],[-5.78,-2.55],[-5.75,-2],[-5.9,-1.23],[-5.8,-.5],[-6.4,.8],[-7.45,1.3]],'The river Baranduin runs south from Lake Evendim past the eastern edge of the Shire.',0),
  river('hoarwell','Hoarwell','Eriador',[[-2.45,-4.7],[-2.82,-4],[-3.05,-3.06],[-2.87,-2.27],[-3.08,-1.25],[-3.65,.15]],'The Hoarwell passes beneath the Last Bridge and receives the Bruinen before the waters reach the Greyflood.',1,'Hoarwell','greyflood'),
  river('bruinen','Bruinen','Eriador',[[-1.48,-3.95],[-1.65,-3.47],[-2.03,-3.04],[-2.3,-2.25],[-3.08,-1.25]],'The Loudwater guards the approaches to Rivendell and joins the Hoarwell.',1,'Bruinen','hoarwell'),
  river('glanduin','Glanduin','Eregion',[[-1.12,-.87],[-1.85,-.48],[-2.5,-.35],[-3.65,.15]],'The southern river of Eregion joins the Hoarwell at the beginning of the Greyflood.',1,'Glanduin','greyflood'),
  river('greyflood','Greyflood','Eriador',[[-3.65,.15],[-4.33,.7],[-5.15,1.03],[-5.84,1.74],[-7.15,2.5]],'The combined waters flow southwest past Tharbad towards the sea.',0),
  river('running','Running River','Rhovanion',[[4.55,-4.5],[4.72,-3.75],[4.72,-3.2],[4.78,-2.65],[5.1,-2],[5.8,-1.3],[6.8,-.8]],'The Celduin flows from Erebor through Long Lake towards the Sea of Rhûn.',0,'Celduin'),
  river('forest-river','Forest River','Northern Mirkwood',[[1.1,-4.85],[1.94,-4.4],[2.8,-4.3],[3.6,-3.85],[4.13,-3.62],[4.72,-3.2]],'Bilbo’s barrel escape followed this river from the Elvenking’s halls towards Long Lake.',1,'Forest River','running'),
  river('isen','Isen','Rohan / Enedwaith',[[-1.7,1.9],[-1.93,2.12],[-2.1,2.5],[-3.2,2.65],[-4.2,2.45],[-5.25,2.68],[-7.1,2.7]],'The western river of Rohan runs past Isengard and the Fords of Isen towards the sea.',0),
  river('adorn','Adorn','Rohan · West-march',[[-2.73,3.38],[-2.9,3.07],[-3.24,2.94],[-3.2,2.65]],'The Adorn joins the Isen and bounds the West-march to the south.',1,'Adorn','isen'),
  river('entwash','Entwash','Rohan',[[-.98,1.05],[-.6,1.2],[.1,1.45],[.48,1.68],[.56,2.1],[.65,2.65],[.78,3.02],[1.19,3.08],[1.68,2.94],[2,2.8]],'From Fangorn, the Entwash crosses Rohan, receives the Snowbourn and divides into a delta at the Anduin.',0,'Entwash','anduin'),
  river('snowbourn','Snowbourn','Rohan · Harrowdale',[[-.55,3.65],[-.43,3.4],[-.4,3.26],[-.41,3.06],[-.18,2.91],[.15,2.98],[.47,3.04],[.78,3.02]],'Rising beneath Starkhorn, the Snowbourn descends Harrowdale, passes Edoras and flows east into the Entwash.',1,'Snowbourn','entwash'),
  river('limlight','Limlight','Northern Rohan',[[-.58,.52],[-.1,.52],[.35,.69],[.86,.75],[1.4,.8]],'This Anduin tributary marks the northern boundary of Rohan.',1,'Limlight','anduin'),
  river('mering','Mering Stream','Rohan / Gondor',[[1.3,3.65],[1.4,3.41],[1.55,3.26],[1.66,3.18]],'Flowing from the Firien Wood, the Mering Stream marks the border with Gondor and enters a southern arm of the Entwash.',1,'Mering Stream','entwash-south'),
  river('entwash-south','Entwash · southern arm','Rohan / Gondor',[[1.19,3.08],[1.44,3.16],[1.66,3.18],[2.24,3.2]],'A schematic southern channel of the Entwash delta, receiving the Mering Stream.',1,'Mouths of Entwash','anduin'),
  river('deeping-stream','Deeping-stream','Rohan · Westfold',[[-1.75,3.24],[-1.7,3.04],[-1.6,2.85],[-1.82,2.63],[-2.1,2.5]],'The stream runs out of Helm’s Deep through the Deeping-coomb towards the Isen.',2,'Deeping-stream','isen'),
  river('silverlode','Silverlode','Lothlórien',[[-.6,-.75],[-.29,-.43],[.03,-.32],[.43,-.12],[1.14,.4]],'The Celebrant runs from the Misty Mountains through Lórien to the Anduin.',1,'Celebrant','anduin'),
  river('nimrodel-river','Nimrodel','Lothlórien',[[-.61,-.25],[-.31,-.21],[.03,-.32]],'The Fellowship crossed this clear stream near the western edge of Lórien.',2,'Nimrodel (river)','silverlode'),
  river('gladden-river','Gladden River','Rhovanion',[[-.47,-1.76],[-.06,-1.63],[.42,-1.78],[.82,-1.4]],'A tributary entering the Anduin at the Gladden Fields.',1,'Gladden River','anduin'),
  river('sirannon','Sirannon','Eregion / Moria',[[-.95,-.5],[-1.4,-.65],[-1.85,-.48]],'The Gate-stream of Moria descends from the West Gate to join the Glanduin.',2,'Sirannon','glanduin'),
  river('morthond','Morthond','Gondor · Blackroot Vale',[[-.6,3.8],[-.8,4.4],[-1.2,5.2],[-1.5,5.9]],'The Blackroot flows south from the Dwimorberg through the Blackroot Vale towards the sea.',1,'Morthond'),
  river('lefnui','Lefnui','Western Gondor',[[-3.2,4.8],[-3.5,5.3],[-3.8,5.9],[-4.2,6.4]],'The western river of Gondor, flowing past the Pinnath Gelin into the sea.',1,'Lefnui'),
  river('ringlo','Ringló','Gondor · Lamedon',[[.2,4.2],[.4,4.7],[.8,5.3],[1.15,5.85]],'Flowing from the White Mountains through Lamedon, the Ringló joins the Gilrain near Linhir.',1,'Ringló')
];
export const lakes=[
  {...entry('nurnen','Sea of Núrnen',8.0,6.12,'Inland sea','Nurn · Southern Mordor','A dark inland sea surrounded by the cultivated lands of Nurn. After Sauron’s defeat, Aragorn gave those lands to the freed slaves.','Sea of Núrnen',0),aliases:['Sea of Nurnen','Nurnen','Lake Nurnen'],rx:1.18,rz:.55},
  {...entry('long-lake','Long Lake',4.72,-3.2,'Lake','Rhovanion','Lake-town stands on this lake south of Erebor, fed by the Running and Forest Rivers.'),rx:.24,rz:.56},
  {...entry('nen-hithoel','Nen Hithoel',1.6,1.56,'Lake','Anduin · Emyn Muil','A lake between the Argonath and the Falls of Rauros. The Fellowship made its last camp on the western shore.','Nen Hithoel'),rx:.21,rz:.39},
  {...entry('evendim','Lake Evendim',-6.27,-4.48,'Lake','Eriador','Nenuial lies north of the Shire. The Brandywine flows from it; Annúminas stood on its shore.','Lake Evendim'),rx:.33,rz:.48},
  {...entry('rhun','Sea of Rhûn',7,-.56,'Inland sea','Rhûn','The great inland sea east of Rhovanion receives the waters of the Celduin.','Sea of Rhûn',0),rx:.66,rz:.46},
];
export const roads=[
  {name:'Harad Road',level:1,points:[[3.8,4.35],[3.85,5.18],[3.08,5.96],[3.15,7.1],[2.8,8.37],[3.45,9.7]]},
  {name:'Morgul Road',level:1,points:[[2.6,4.35],[2.9,4.1],[3.44,4.3],[3.98,4.48]]},
  {name:'Great West Road',level:1,points:[[-2.1,2.5],[-1.3,2.72],[-.3,3],[.35,3.18],[1.3,3.52],[1.95,3.88],[2.6,4.35]]},
  {name:'Road to Dunharrow',level:2,points:[[-.3,3],[-.4,3.26],[-.35,3.46]]},
  {name:'East Road',level:1,points:[[-8.1,-2.3],[-6.5,-2.6],[-4.65,-2.5],[-3.65,-2.75],[-3.05,-3.06],[-2.65,-3.15],[-2.03,-3.04],[-1.8,-3.3]]}
];
// Pixels per map unit, not raw camera distance: consistent on small screens.
export function detailLevel(pixelsPerUnit) { return pixelsPerUnit>=190?2:pixelsPerUnit>=105?1:0; }
export const geographyEntries=[...localPlaces,...localAreas,...rivers,...lakes];
